spring.application.name=spring-boot-samples-kafka
server.port=8081
spring.main.allow-bean-definition-overriding=true
#spring.kafka.bootstrap-servers=marketing-kafka-n1.bestpay.46-mid:9092,marketing-kafka-n2.bestpay.46-mid:9092,marketing-kafka-n3.bestpay.46-mid:9092
spring.kafka.bootstrap-servers=marketing-kafka-n1.bestpay.46-mid:9092,marketing-kafka-n2.bestpay.46-mid:9092,marketing-kafka-n3.bestpay.46-mid:9092


